### ISSUE TITLE
프로젝트명 관련 문의

### ISSUE THREAD

**Issue by heisice** [no-commit-today/tech-swipe-front#77]
안녕하세요.

저는 테크스와이프라는 회사를 운영하고 있는 김기수입니다.

저는 테크스와이프라는 이름을 2018년부터 사업자 등록과 함께 회사명으로 사용해오고 있습니다. 최근에 저희 회사 웹사이트의 내용을 개선하면서 검색 키워드를 관리하던 중, 귀사의 프로젝트를 발견하게 되어 이렇게 연락드리게 되었습니다.

죄송한 말씀입니다만, 저희 회사의 이름을 변경하는 것은 현실적으로 큰 어려움이 따릅니다. 혹시 가능하시다면, 프로젝트명 변경을 검토해 주실 수 있을지 문의드립니다.

저희와 이름이 검색 엔진에 동시에 노출될 경우, 상호 간에 혼란이나 피해가 발생할 우려가 있어 이 같은 요청을 드리게 되었습니다.

귀중한 시간을 할애하여 이 문제를 검토해 주시면 대단히 감사하겠습니다.

감사합니다.

테크스와이프 (https://techswipe.co.kr)
김기수 드림.

[contact@techswipe.co.kr](mailto:contact@techswipe.co.kr)

**Comment by prkgnt** [comment]
안녕하세요. 문의주신 내용 관련하여 이메일로 답변드렸습니다!
